fix: try refreshing cookie on multiple cases
ueberauth/guardian pull request #683
Opened 2021-08-17 14:02 UTC by StephaneRob

Currently we try to refresh cookie only when the access token is found and is expired.
If the refresh cookie is present we should try refreshing session with it even if invalid or not found.

2021-08-17 19:34 UTC, yordis commented
Would you mind adding an entry in the changelog https://github.com/ueberauth/guardian/blob/master/CHANGELOG.md

2021-08-17 21:26 UTC, yordis requested changes
Please add some entry in the changelog so we keep the PR ready to be release

2021-08-18 06:17 UTC, StephaneRob commented
Hi @yordis, I added some test cases and updated the CHANGELOG.
The changelog doesn't mention the neither `refresh_from_cookie` option nor `VerifyCookie` plug deprecation. Do you want I add it under `2.2.0` version?

2021-08-18 06:33 UTC, yordis commented
@StephaneRob please if you don't mind I would appreciate updating the CHANGELOG for sure

2021-08-18 06:44 UTC, StephaneRob commented
@yordis done.

2021-08-18 06:51 UTC, yordis commented
You are the best! Thank you so much!

2021-08-18 06:51 UTC, yordis approved these changes

2021-08-18 06:51 UTC, merged