Fix error when authorization header is nil
ueberauth/guardian pull request #729
Opened 2024-04-19 09:27 UTC by koszta

Fix error with Bandit when a client sends an empty Authorization header.

```
** (FunctionClauseError) no function clause matching in String.trim/1
    (elixir 1.16.2) lib/string.ex:1293: String.trim(nil)
    (guardian 2.3.2) lib/guardian/plug/verify_header.ex:167: Guardian.Plug.VerifyHeader.fetch_token_from_header/3
    (guardian 2.3.2) lib/guardian/plug/verify_header.ex:88: Guardian.Plug.VerifyHeader.call/2
    (api 0.0.1) ApiWeb.Router.guardian/2
    (api 0.0.1) lib/api_web/router.ex:1: ApiWeb.Router.__pipe_through0__/1
    (phoenix 1.7.12) lib/phoenix/router.ex:475: Phoenix.Router.__call__/5
    (api 0.0.1) deps/plug/lib/plug/error_handler.ex:80: ApiWeb.Router.call/2
    (api 0.0.1) lib/api_web/endpoint.ex:1: ApiWeb.Endpoint.plug_builder_call/2
Last message: {:continue, :start_stream}
```

2024-04-19 11:23 UTC, paulswartz reviewed
This seems like a bug in Bandit? The [type of req_headers](https://hexdocs.pm/plug/Plug.Conn.html#t:headers/0) says the value should always be a `binary()`.

2024-05-17 15:09 UTC, yordis commented
@koszta do you mind confirming that this is an expected behavior and it is not a bug in Bandit or something else?

2024-05-17 15:17 UTC, yordis requested changes
@koszta do you mind confirming that this is an expected behavior and it is not a bug in Bandit or something else?

2024-07-17 11:41 UTC, koszta commented
yes, it's clearly a bandit bug, closing it

2024-07-17 11:41 UTC, closed without merging